version: '3.2'
services:
  run-all:
    image: playwright-test
    command: "yarn run test"
    volumes:
      - /usr/local/var/buildkite-agent/builds/OFedore-M-3JD93-1/test-org-50/test-pipeline/playwright-tests/playwright-report:/app/playwright-report
      - /usr/local/var/buildkite-agent/builds/OFedore-M-3JD93-1/test-org-50/test-pipeline/playwright-tests/test-results:/app/test-results